### ISSUE TITLE
Final Request for Help

### ISSUE THREAD

**Issue by paulsamaroo** [tonyvu2014/android-shoppingcart#10]
Hi, sorry to bother you once again, however, this is the final thing I need help with in terms of fully implementing your Shopping Cart system within my app. Maybe you can give me advice, or point me in the right direction. (I apologise if this is not the correct place to do this). I am essentially trying to create a "Re-Order" system; meaning that after the user places an order, then the system will store that order in either an online database or in a session on the device. So, if the user clicks the "Re-Order" button, their cart will be updated with the items which they previously had ordered.

Currently, I have the system set up to email me the order when the user places the order, and store the string in the database. However, I am not certain as how to approach updating the shopping cart with the corresponding items of that order. I'm thinking I need to create a separate table for orders, but I am not sure how to update the shopping cart with the order info (for example, if I order 3 items, I would store those items in a database on 3 separate rows of Item Name, Quantity, and Unit Price. Then I would need to pull that data from the database, and populate the shopping cart with said data).

 Any help will be greatly appreciated.

**Comment by tonyvu2014** [comment]
For that, I think you need to look at either storing the order in a DB or a Shared Preferences. Have a look at SQLite http://www.vogella.com/tutorials/AndroidSQLite/article.html or Shared Preferences https://developer.android.com/reference/android/content/SharedPreferences.html.

**Comment by paulsamaroo** [comment]
Hi, yes I agree, however, in order to place the items back in the cart, I
would have to store the individual attributes of each order item right? If
so, is there a way to access that data using CartItem?

## 

Paul Samaroo
Trinidad
West Indies
Tel: 868 490 5799
https://www.facebook.com/pages/BITS-Binary-IT-Solutions/414537758582184?fref=ts

**Comment by tonyvu2014** [comment]
My demo project is just for demonstration purpose of the shopping cart module usage. For a full-fledged working e-commerce app, you definitely should store the data on server DB and retrieve from there through API.
