### ISSUE TITLE
How to integrate this library with a project in Android Studio?

### ISSUE THREAD

**Issue by khurana3192** [tonyvu2014/android-shoppingcart#2]
^

**Comment by tonyvu2014** [comment]
@khurana3192,  there is a pull request to migrate this project to  gradle. I will merge it soon

**Comment by khurana3192** [comment]
@tonyvu2014 Hi,

I was to able to run both demo project and library in android studio. If you want I can make pointers for that.

Right now I am stuck in a problem.

You are adding products to cart in a separate activity ie. ProductActivity.

However my use case requires me to add products in the main activity using + and - buttons.

Your library fails to detect that product is already there in the cart as my memory hash of the product class changes every time the list refreshes.

Thus I get two copies of same product in the cart if my list refreshes.

Can u help me with this?

**Comment by tonyvu2014** [comment]
Hi @khurana3192 from what you said, it seems like the hashCode() method of the Product class was not correctly implemented. Can you share your Product class.
