### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by willbun244** [tonyvu2014/android-shoppingcart#3]
How can I add images to the product? Please provide source code.

**Comment by tonyvu2014** [comment]
Hi @willbun244,  this project is meant to provide the base only, to add image for product, you need to import this android-shoppingcart project and extend Saleable interface. Would you like to do that on android-shoppingcart-demo (https://github.com/tonyvu2014/android-shoppingcart-demo) project and make a pull request? I am happy to merge. Thanks.

**Comment by willbun244** [comment]
Yes of course! Ok, I will.

**Comment by tonyvu2014** [comment]
product images have been added to demo project
