### ISSUE TITLE
Adding image to each item

### ISSUE THREAD

**Issue by paulsamaroo** [tonyvu2014/android-shoppingcart#5]
Hi, is it possible to add an image onto each product in the product list, and/or shopping cart? If so, can you let me know how to? Thank you very much!

**Comment by tonyvu2014** [comment]
Hi @paulsamaroo , of course you can. Create a Product class that extend Saleable class and include a property for product image url. The example under https://github.com/tonyvu2014/android-shoppingcart/tree/master/demo is without the images but you definitely can add in. Feel free to make a pull request for adding image to demo product. I am happy to merge. Thanks.

**Comment by paulsamaroo** [comment]
Hi, I'm very new to GitHub, so I don't know what you mean by "make a pull request for adding image to demo product". I apologise for my ignorance.

**Comment by paulsamaroo** [comment]
can we discuss over email or skype?

**Comment by tonyvu2014** [comment]
What I mean is that you can clone the project, make changes to include the product images and commit to my repository. I will review and merge.

**Comment by paulsamaroo** [comment]
ok I uploaded the files, but how do I commit to your repository?

## 

Paul Samaroo
Trinidad
West Indies
Tel: 868 490 5799
https://www.facebook.com/pages/BITS-Binary-IT-Solutions/414537758582184?fref=ts

**Comment by paulsamaroo** [comment]
okay I created the pull request

## 

Paul Samaroo
Trinidad
West Indies
Tel: 868 490 5799
https://www.facebook.com/pages/BITS-Binary-IT-Solutions/414537758582184?fref=ts

**Comment by tonyvu2014** [comment]
Why are there so many changes? I would expect to see the changes in Product and ProductActivity classes only.

**Comment by paulsamaroo** [comment]
I went ahead and did two things...since i'm still getting the hang of it...

I re-uploaded the class with the changes to my repository

I edited the two files from the link which you sent to include the changes
I made.

Hopefully one of those were correct lol.

## 

Paul Samaroo
Trinidad
West Indies
Tel: 868 490 5799
https://www.facebook.com/pages/BITS-Binary-IT-Solutions/414537758582184?fref=ts

**Comment by paulsamaroo** [comment]
by the way, the reason why it has so many "changes" is because I used
gradle to import it into android studio.

## 

Paul Samaroo
Trinidad
West Indies
Tel: 868 490 5799
https://www.facebook.com/pages/BITS-Binary-IT-Solutions/414537758582184?fref=ts

**Comment by paulsamaroo** [comment]
Hey don't forget me please. I think I did the correct thing this time...by just changing the necessary files. Please advise.

**Comment by tonyvu2014** [comment]
Ok will update soon

**Comment by tonyvu2014** [comment]
Hi @paulsamaroo 

I have added images to each product in the demo project. You can check it out.

**Comment by paulsamaroo** [comment]
OMG! Thank you! Works perfectly! :D You're amazing
