### ISSUE TITLE
Deleting Individual Items from Shopping Cart

### ISSUE THREAD

**Issue by paulsamaroo** [tonyvu2014/android-shoppingcart#9]
Is it possible to delete individual items from shopping cart?

**Comment by paulsamaroo** [comment]
I went ahead and did the following, however, I noticed that when I click on the first two items in the shopping cart, they have the wrong name; they have the name of a different product.

lvCartItems.setOnItemLongClickListener(new AdapterView.OnItemLongClickListener(){
            @Override
            public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
                Product product = Constant.PRODUCT_LIST.get(position - 1);
                Toast.makeText(ShoppingCartActivity.this, "You have long clicked " + product.getName(), Toast.LENGTH_SHORT).show();
                return false;
            }
        });

**Comment by tonyvu2014** [comment]
Do you meant o remove 1 item from the shopping cart? It is definitely possible

**Comment by paulsamaroo** [comment]
Yes, I would like it work in such a way so that when I long click an item from the shopping cart list, then a prompt will appear asking the user to delete the item from cart. The code I typed above doesn't work, so I was wondering if you could point me in the right direction? :)

**Comment by tonyvu2014** [comment]
It does not work because you did not perform the removal on the shopping cart. You should look at using remove() method from Cart class. Remember to call notifyDataSetChange() after that to update the ListView.

**Comment by paulsamaroo** [comment]
Yes, but before I reach that stage, I just wanted to test if the code knows which item I am clicking on, by showing a Toast with the item's name. However, it does not show the name of the item I click, but rather the name of the item before it in the listview.

**Comment by tonyvu2014** [comment]
Then the issue is with `position-1` , you should use `position` instead

**Comment by paulsamaroo** [comment]
I tried that as well, however, I get the indexoutofboundsexception

**Comment by tonyvu2014** [comment]
ok will look at it this weekend

**Comment by paulsamaroo** [comment]
Okay thank you :)

**Comment by tonyvu2014** [comment]
I think the key is to understand that you want to delete the product item from the shopping cart, so try something like this:

```
lvCartItems.setOnItemLongClickListener(new AdapterView.OnItemLongClickListener() {
            @Override
            public boolean onItemLongClick(AdapterView<?> parent, View view, int position, long id) {
                List<CartItem> cartItems = getCartItems(cart);
                cart.remove(cartItems.get(position-1).getProduct());
                cartItems.remove(position-1);
                cartItemAdapter.updateCartItems(cartItems);
                cartItemAdapter.notifyDataSetChanged();
                tvTotalPrice.setText(Constant.CURRENCY+String.valueOf(cart.getTotalPrice().setScale(2, BigDecimal.ROUND_HALF_UP)));
                return false;
            }
        });
```

**Comment by paulsamaroo** [comment]
Ah! Yes!! I understand now...I also got it to print out the correct names of the products as well :D Thank you!

**Comment by paulsamaroo** [comment]
By the way...I wanted to try one other thing regarding the shopping cart activity...if the user clicks (not long click), they should be redirected to the corresponding product page. However, this doesn't work properly with the following code...

lvCartItems.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> parent, View view,
                                    int position, long id) {
                Product product = Constant.PRODUCT_LIST.get(position-1);
                Intent intent = new Intent(ShoppingCartActivity.this, ProductActivity.class);
                Bundle bundle = new Bundle();
                bundle.putSerializable("product", product);
                Log.d(TAG, "View product: " + product.getName());
                intent.putExtras(bundle);
                startActivity(intent);
            }
        });
